spring.application.name=LogSentry

server.port=8080

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Logging
logging.level.org.springframework=INFO
logging.level.com.develop=DEBUG

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto: none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Swagger
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.path=/swagger

# JWT
jwt.secret.key=${JWT_SECRET}

# Admin_Key
admin.key=${ADMIN_KEY}

# MySQL (Docker)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/${DB_NAME}?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

## Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.topic.log=logs-topic

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=log-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.develop.logsentry.domain.log.dto.request.*
spring.kafka.consumer.properties.spring.json.value.default.type=com.develop.logsentry.domain.log.dto.request.LogMessageDto